import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'heritage-hoodie-noir',
    name: 'HERITAGE HOODIE',
    variant: 'NOIR',
    price: 185,
    currency: 'USD',
    image: '/images/IMG_4340.JPG',
    gallery: ['/images/IMG_4340.JPG', '/images/3E8CC15F-49F3-47F7-BC52-CDA9F08732B9.jpg'],
    colors: [
      { name: 'Noir', hex: '#000000', slug: 'noir' },
      { name: 'Charcoal', hex: '#2a2a2a', slug: 'charcoal' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stockStatus: 'in_stock',
    description: 'Forged from 450GSM heavyweight cotton, the Heritage Hoodie carries the weight of legacy. Its double-layer construction wraps you in an enveloping warmth, while the brushed gold insignia on the chest marks you as part of something larger. Broad-shouldered, slightly oversized — a silhouette designed from the ground up.',
    culturalInspiration: 'Inspired by Kuba Kingdom cloth artistry from the Democratic Republic of Congo — the gold insignia echoes centuries of royal African craftsmanship.',
    composition: '450GSM — Outer: 80% Cotton, 20% Polyester. Inner: 92% Cotton, 8% Polyester.',
    care: 'Wash inside out at 30°C. Do not tumble dry. Do not bleach. Iron on low, avoid direct contact with gold insignia.',
    badge: 'BESTSELLER',
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'kuba-bomber-eclipse',
    name: 'KUBA BOMBER',
    variant: 'ECLIPSE',
    price: 245,
    currency: 'USD',
    image: '/images/3E8CC15F-49F3-47F7-BC52-CDA9F08732B9.jpg',
    gallery: ['/images/3E8CC15F-49F3-47F7-BC52-CDA9F08732B9.jpg', '/images/IMG_4340.JPG'],
    colors: [
      { name: 'Eclipse', hex: '#0a0a0a', slug: 'eclipse' },
      { name: 'Midnight', hex: '#1a1a2e', slug: 'midnight' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stockStatus: 'low_stock',
    description: 'The Kuba Bomber is architecture in motion. Satin-finish shell with hand-stitched geometric banding along the shoulders and cuffs — each pattern drawn from Kuba Kingdom royal cloth traditions. A statement piece that speaks before you do.',
    culturalInspiration: 'The geometric gold banding is a direct homage to Kuba raffia cloth — woven by the Kuba Kingdom of central Africa, historically worn by royalty and worn at ceremonies of great significance.',
    composition: '100% Polyester Satin Shell. Gold banding: 60% Metallic Thread, 40% Cotton.',
    care: 'Dry clean recommended. Spot clean with damp cloth. Do not machine wash.',
    badge: 'LIMITED',
    isNew: true,
    isFeatured: true,
  },
  {
    id: '3',
    slug: 'adire-tee-obsidian',
    name: 'ADIRE TEE',
    variant: 'OBSIDIAN',
    price: 95,
    currency: 'USD',
    image: '/images/EC5DA517-0A9A-422B-B7EA-9EF99BE80DA5.PNG',
    gallery: ['/images/EC5DA517-0A9A-422B-B7EA-9EF99BE80DA5.PNG', '/images/F137AD08-1511-4F6A-BFAD-B0E176D6A21C.PNG'],
    colors: [
      { name: 'Obsidian', hex: '#050505', slug: 'obsidian' },
      { name: 'Deep Navy', hex: '#0a0a1a', slug: 'deep-navy' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stockStatus: 'in_stock',
    description: 'The Adire Tee carries culture on its chest. Heavyweight 220GSM cotton, pre-washed for a lived-in softness, with a full-front gold foil print translating Yoruba Adire textile patterns into streetwear language. Oversized cut, dropped shoulders, raw hem.',
    culturalInspiration: 'Adire is a Yoruba tradition of resist-dyeing cloth using indigo — practised for centuries in West Africa. The gold print reimagines these geometric resist patterns in a contemporary context.',
    composition: '220GSM — 100% Pre-washed Cotton. Gold print: Water-based foil ink.',
    care: 'Machine wash cold, inside out. Tumble dry low. Do not iron directly on print.',
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'ndebele-joggers-shadow',
    name: 'NDEBELE JOGGERS',
    variant: 'SHADOW',
    price: 145,
    currency: 'USD',
    image: '/images/F137AD08-1511-4F6A-BFAD-B0E176D6A21C.PNG',
    gallery: ['/images/F137AD08-1511-4F6A-BFAD-B0E176D6A21C.PNG', '/images/EC5DA517-0A9A-422B-B7EA-9EF99BE80DA5.PNG'],
    colors: [
      { name: 'Shadow', hex: '#000000', slug: 'shadow' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stockStatus: 'in_stock',
    description: 'Cut for movement, built for presence. The Ndebele Joggers feature a tapered silhouette with gold metallic side tape — its geometric pattern directly sourced from Ndebele beadwork traditions. Elasticated waistband with gold-finish drawstring, ribbed ankle cuffs.',
    culturalInspiration: 'The Ndebele people of South Africa are renowned for their vibrant geometric beadwork and mural paintings. The gold side stripe is a direct abstraction of their diamond and triangle pattern vocabulary.',
    composition: '340GSM — 80% Cotton, 20% Polyester. Side tape: 70% Metallic Polyester, 30% Cotton.',
    care: 'Machine wash cold, inside out. Tumble dry low. Do not bleach.',
    isNew: true,
    isFeatured: true,
  },
]

export const getFeaturedProducts = () => products.filter(p => p.isFeatured)
export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug)
export const getProductById = (id: string) => products.find(p => p.id === id)
